# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='A short, unique string that will represent this object in URLs.', unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='open', help_text='Status of registration.', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='choices_enabled',
            field=models.BooleanField(default=False, help_text="Whether or not to show choices. This doesn't disable actually having choices, however."),
        ),
    ]
